// ─────────────────────────────────────────────────────────────
//  TalentForge AI — Candidate Module Centralized Mock Data
// ─────────────────────────────────────────────────────────────

// ── Candidate Profile ──────────────────────────────────────
export const profileData = {
  id: 'cand_001',
  name: 'Aaryan ',
  initials: 'AS',
  title: 'Senior Frontend Developer',
  location: 'Bangalore, India',
  email: 'aaryan.singh@email.com',
  phone: '+91 98765 43210',
  website: 'https://aaryansingh.dev',
  github: 'https://github.com/aaryansingh',
  linkedin: 'https://linkedin.com/in/aaryansingh',
  portfolio: 'https://aaryansingh.dev/portfolio',
  bio: 'Passionate Frontend Developer with 4+ years of experience building high-performance web applications. Specialized in React, TypeScript, and modern CSS. Love creating delightful user experiences.',
  avatarColor: 'from-blue-500 to-blue-700',
  profileCompletion: 65,
  completionChecklist: [
    { label: 'Basic Information', done: true },
    { label: 'Work Experience', done: true },
    { label: 'Skills', done: true },
    { label: 'Education', done: false },
    { label: 'Resume', done: false },
  ],
  skills: ['React', 'TypeScript', 'Next.js', 'JavaScript', 'Tailwind CSS', 'Node.js', 'GraphQL', 'REST APIs', 'Git', 'Figma'],
  experience: [
    {
      id: 'exp_1',
      company: 'Infosys',
      role: 'Senior Frontend Developer',
      duration: 'Jan 2022 – Present',
      location: 'Bangalore, India',
      description: 'Led frontend development for enterprise SaaS products. Built scalable component libraries using React and TypeScript. Improved core web vitals by 40%.',
      logo: '🟦',
    },
    {
      id: 'exp_2',
      company: 'Wipro',
      role: 'Frontend Developer',
      duration: 'Jun 2020 – Dec 2021',
      location: 'Pune, India',
      description: 'Developed responsive web applications for banking clients. Collaborated with UX designers and backend engineers.',
      logo: '🟠',
    },
  ],
  education: [
    {
      id: 'edu_1',
      institution: 'IIT Bombay',
      degree: 'B.Tech in Computer Science',
      duration: '2016 – 2020',
      grade: '8.4 CGPA',
    },
  ],
  resume: {
    name: 'Aaryan_Singh_Resume_2024.pdf',
    size: '248 KB',
    uploaded: 'May 10, 2024',
    url: '#',
  },
};

// ── Jobs ───────────────────────────────────────────────────
export const jobsData = [
  {
    id: 'job_1',
    title: 'Frontend Developer',
    company: 'Google',
    companyLogo: 'G',
    companyColor: 'bg-blue-600',
    location: 'Bangalore, India',
    type: 'Remote',
    salary: '₹18 – ₹28 LPA',
    experience: '3-5 years',
    match: 95,
    posted: '2 days ago',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    saved: true,
    description: 'We are looking for a passionate Frontend Developer to join our team and help build amazing user experiences at scale. You will work with a world-class engineering team on products used by billions of people.',
    responsibilities: [
      'Build responsive and user-friendly web applications',
      'Collaborate with designers and backend engineers',
      'Optimize application performance for speed and scalability',
      'Mentor junior developers and conduct code reviews',
    ],
    requirements: [
      '3-5 years of experience in Frontend development',
      'Strong proficiency in React and TypeScript',
      'Experience with modern CSS frameworks',
      'Familiarity with RESTful APIs and GraphQL',
    ],
    benefits: ['Competitive salary', 'Health insurance', 'Stock options', 'Remote work flexibility', 'Learning budget'],
    department: 'Engineering',
    deadline: 'Jun 30, 2024',
  },
  {
    id: 'job_2',
    title: 'UI/UX Designer',
    company: 'Microsoft',
    companyLogo: 'M',
    companyColor: 'bg-orange-500',
    location: 'Noida, India',
    type: 'Hybrid',
    salary: '₹12 – ₹20 LPA',
    experience: '2-4 years',
    match: 92,
    posted: '1 day ago',
    skills: ['Figma', 'UI Design', 'Prototyping', 'User Research'],
    saved: false,
    description: 'Join Microsoft\'s design team to create intuitive and beautiful experiences for millions of users worldwide.',
    responsibilities: [
      'Design user interfaces for enterprise software products',
      'Conduct user research and usability testing',
      'Create wireframes, prototypes, and high-fidelity mockups',
      'Collaborate with product managers and engineers',
    ],
    requirements: [
      '2-4 years of UI/UX design experience',
      'Proficiency in Figma and Adobe Creative Suite',
      'Strong portfolio demonstrating design thinking',
      'Experience with design systems',
    ],
    benefits: ['Competitive salary', 'Hybrid work model', 'Employee discounts', 'Health & wellness'],
    department: 'Design',
    deadline: 'Jul 5, 2024',
  },
  {
    id: 'job_3',
    title: 'Full Stack Developer',
    company: 'Infosys',
    companyLogo: 'I',
    companyColor: 'bg-indigo-600',
    location: 'Pune, India',
    type: 'Remote',
    salary: '₹10 – ₹16 LPA',
    experience: '2-4 years',
    match: 90,
    posted: '3 days ago',
    skills: ['Node.js', 'React', 'MongoDB', 'AWS'],
    saved: false,
    description: 'Build and maintain full-stack applications for our enterprise clients across various domains.',
    responsibilities: [
      'Develop RESTful APIs and microservices',
      'Build React-based frontend applications',
      'Design and optimize database schemas',
      'Deploy and monitor applications on AWS',
    ],
    requirements: [
      '2-4 years of full-stack development experience',
      'Proficiency in Node.js and React',
      'Experience with MongoDB or PostgreSQL',
      'Knowledge of cloud platforms (AWS preferred)',
    ],
    benefits: ['Flexible hours', 'Remote work', 'Performance bonuses', 'Career development'],
    department: 'Engineering',
    deadline: 'Jun 28, 2024',
  },
  {
    id: 'job_4',
    title: 'Backend Engineer (Go)',
    company: 'Swiggy',
    companyLogo: 'S',
    companyColor: 'bg-orange-500',
    location: 'Bangalore, India',
    type: 'Hybrid',
    salary: '₹15 – ₹25 LPA',
    experience: '3-5 years',
    match: 88,
    posted: '5 days ago',
    skills: ['Go', 'Redis', 'PostgreSQL', 'Docker'],
    saved: false,
    description: 'Join Swiggy\'s backend team to build highly scalable systems that handle millions of orders every day.',
    responsibilities: [
      'Design and build high-performance microservices in Go',
      'Optimize database queries and caching strategies',
      'Work on distributed systems and event-driven architectures',
    ],
    requirements: [
      '3-5 years of backend development experience',
      'Strong proficiency in Go',
      'Experience with distributed systems',
      'Knowledge of containerization with Docker/Kubernetes',
    ],
    benefits: ['ESOPs', 'Free meals', 'Health insurance', 'Work-life balance'],
    department: 'Engineering',
    deadline: 'Jul 10, 2024',
  },
  {
    id: 'job_5',
    title: 'Product Designer',
    company: 'Ola',
    companyLogo: 'O',
    companyColor: 'bg-yellow-500',
    location: 'Bangalore, India',
    type: 'Remote',
    salary: '₹12 – ₹22 LPA',
    experience: '2-5 years',
    match: 72,
    posted: '1 week ago',
    skills: ['Figma', 'Product Strategy', 'User Research', 'Design Systems'],
    saved: true,
    description: 'Shape the future of mobility by designing intuitive product experiences for Ola\'s growing platform.',
    responsibilities: [
      'Own end-to-end product design for key features',
      'Collaborate with PMs to define product vision',
      'Build and maintain design systems',
    ],
    requirements: [
      '2-5 years of product design experience',
      'Strong portfolio with mobile and web products',
      'Experience with data-driven design decisions',
    ],
    benefits: ['ESOPs', 'Remote work', 'Health coverage', 'Transport allowance'],
    department: 'Design',
    deadline: 'Jul 15, 2024',
  },
  {
    id: 'job_6',
    title: 'React Native Developer',
    company: 'Zomato',
    companyLogo: 'Z',
    companyColor: 'bg-red-500',
    location: 'Gurgaon, India',
    type: 'On-site',
    salary: '₹14 – ₹22 LPA',
    experience: '2-4 years',
    match: 85,
    posted: '4 days ago',
    skills: ['React Native', 'TypeScript', 'Redux', 'iOS/Android'],
    saved: false,
    description: 'Build the next generation of Zomato\'s mobile apps used by millions of food lovers.',
    responsibilities: [
      'Develop and maintain React Native mobile applications',
      'Write clean, testable, and maintainable code',
      'Collaborate with product and design teams',
    ],
    requirements: [
      '2-4 years of React Native experience',
      'Experience publishing to App Store and Play Store',
      'Strong JavaScript/TypeScript skills',
    ],
    benefits: ['Free lunch', 'Flexible hours', 'Health insurance'],
    department: 'Mobile Engineering',
    deadline: 'Jul 8, 2024',
  },
];

// ── Companies ──────────────────────────────────────────────
export const companiesData = [
  {
    id: 'co_1',
    name: 'Google',
    logo: 'G',
    logoColor: 'bg-blue-600',
    industry: 'Computer Software',
    location: 'Mountain View, CA, USA',
    size: '1,90,234',
    founded: '1998',
    type: 'Public Company',
    website: 'https://google.com',
    rating: 4.6,
    reviewCount: 12345,
    openJobs: 125,
    overview: "Google's mission is to organize the world's information and make it universally accessible and useful. Our products and platforms — including Search, YouTube, Android, Google Cloud, and Google Drive — help billions of people every day.",
    culture: 'Innovative & collaborative',
    careerGrowth: 'High opportunities',
    employeeRating: '4.6/5',
    ceo: 'Sundar Pichai',
    highlights: ['Work Culture', 'Career Growth', 'Employee Rating'],
    ratingBreakdown: { 5: 72, 4: 18, 3: 6, 2: 2, 1: 2 },
    reviews: [
      { name: 'Rohan Mehta', role: 'Software Engineer', date: '7 days ago', rating: 5, pros: 'Amazing place to work with smart and humble people. Great learning opportunities and work-life balance.', cons: 'Promotion cycles can be slow.', helpful: 123, unhelpful: 12 },
      { name: 'Priya Sharma', role: 'Product Manager', date: '2 weeks ago', rating: 4, pros: 'Excellent culture and benefits. Cutting-edge projects.', cons: 'Highly competitive environment.', helpful: 89, unhelpful: 5 },
    ],
    photos: ['office1', 'office2', 'office3'],
    verified: true,
    bannerColor: 'from-blue-600 to-blue-800',
  },
  {
    id: 'co_2',
    name: 'Microsoft',
    logo: 'M',
    logoColor: 'bg-orange-500',
    industry: 'Computer Software',
    location: 'Redmond, WA, USA',
    size: '2,21,000',
    founded: '1975',
    type: 'Public Company',
    website: 'https://microsoft.com',
    rating: 4.5,
    reviewCount: 9823,
    openJobs: 98,
    overview: 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide.',
    culture: 'Growth mindset',
    careerGrowth: 'Excellent',
    employeeRating: '4.5/5',
    ceo: 'Satya Nadella',
    highlights: ['Work-Life Balance', 'Benefits', 'Innovation'],
    ratingBreakdown: { 5: 65, 4: 22, 3: 9, 2: 3, 1: 1 },
    reviews: [
      { name: 'Arjun Kumar', role: 'Software Engineer', date: '3 days ago', rating: 5, pros: 'Great culture and work-life balance. Excellent compensation package.', cons: 'Large company can feel bureaucratic.', helpful: 78, unhelpful: 4 },
    ],
    photos: [],
    verified: true,
    bannerColor: 'from-slate-700 to-slate-900',
  },
  {
    id: 'co_3',
    name: 'Infosys',
    logo: 'I',
    logoColor: 'bg-indigo-600',
    industry: 'IT Services',
    location: 'Bangalore, India',
    size: '3,14,000',
    founded: '1981',
    type: 'Public Company',
    website: 'https://infosys.com',
    rating: 4.2,
    reviewCount: 34521,
    openJobs: 62,
    overview: 'Infosys is a global leader in next-generation digital services and consulting, helping clients navigate digital transformation.',
    culture: 'Learning focused',
    careerGrowth: 'Structured',
    employeeRating: '4.2/5',
    ceo: 'Salil Parekh',
    highlights: ['Training', 'Stability', 'Global Projects'],
    ratingBreakdown: { 5: 45, 4: 30, 3: 15, 2: 7, 1: 3 },
    reviews: [],
    photos: [],
    verified: true,
    bannerColor: 'from-indigo-700 to-indigo-900',
  },
  {
    id: 'co_4',
    name: 'Amazon',
    logo: 'A',
    logoColor: 'bg-yellow-600',
    industry: 'E-Commerce / Cloud',
    location: 'Seattle, WA, USA',
    size: '15,00,000',
    founded: '1994',
    type: 'Public Company',
    website: 'https://amazon.com',
    rating: 4.1,
    reviewCount: 54321,
    openJobs: 80,
    overview: 'Amazon is guided by four principles: customer obsession, passion for invention, commitment to operational excellence, and long-term thinking.',
    culture: 'Customer obsessed',
    careerGrowth: 'Fast-paced',
    employeeRating: '4.1/5',
    ceo: 'Andy Jassy',
    highlights: ['Ownership', 'Innovation', 'Compensation'],
    ratingBreakdown: { 5: 50, 4: 25, 3: 14, 2: 8, 1: 3 },
    reviews: [],
    photos: [],
    verified: true,
    bannerColor: 'from-yellow-600 to-orange-600',
  },
  {
    id: 'co_5',
    name: 'Swiggy',
    logo: 'S',
    logoColor: 'bg-orange-500',
    industry: 'Food Tech',
    location: 'Bangalore, India',
    size: '5,000+',
    founded: '2014',
    type: 'Private',
    website: 'https://swiggy.com',
    rating: 4.0,
    reviewCount: 3214,
    openJobs: 45,
    overview: 'Swiggy is India\'s leading on-demand delivery platform with a tech-first approach to logistics.',
    culture: 'Startup energy',
    careerGrowth: 'Rapid',
    employeeRating: '4.0/5',
    ceo: 'Sriharsha Majety',
    highlights: ['Fast Growth', 'ESOPs', 'Innovation'],
    ratingBreakdown: { 5: 40, 4: 35, 3: 15, 2: 7, 1: 3 },
    reviews: [],
    photos: [],
    verified: false,
    bannerColor: 'from-orange-600 to-red-600',
  },
  {
    id: 'co_6',
    name: 'Zomato',
    logo: 'Z',
    logoColor: 'bg-red-500',
    industry: 'Food Tech',
    location: 'Gurgaon, India',
    size: '3,500+',
    founded: '2008',
    type: 'Public Company',
    website: 'https://zomato.com',
    rating: 3.9,
    reviewCount: 2841,
    openJobs: 38,
    overview: 'Zomato is an Indian multinational restaurant aggregator and food delivery company.',
    culture: 'Fast and dynamic',
    careerGrowth: 'Good',
    employeeRating: '3.9/5',
    ceo: 'Deepinder Goyal',
    highlights: ['Free Food', 'Equity', 'Culture'],
    ratingBreakdown: { 5: 38, 4: 32, 3: 18, 2: 8, 1: 4 },
    reviews: [],
    photos: [],
    verified: true,
    bannerColor: 'from-red-600 to-red-800',
  },
  {
    id: 'co_7',
    name: 'Ola',
    logo: 'O',
    logoColor: 'bg-yellow-500',
    industry: 'Mobility / EV',
    location: 'Bangalore, India',
    size: '10,000+',
    founded: '2010',
    type: 'Private',
    website: 'https://olacabs.com',
    rating: 3.8,
    reviewCount: 1923,
    openJobs: 25,
    overview: 'Ola is India\'s largest mobility platform, now expanding into electric vehicles and clean energy.',
    culture: 'Mission-driven',
    careerGrowth: 'Growing fast',
    employeeRating: '3.8/5',
    ceo: 'Bhavish Aggarwal',
    highlights: ['EV Revolution', 'Scale', 'India First'],
    ratingBreakdown: { 5: 32, 4: 33, 3: 20, 2: 10, 1: 5 },
    reviews: [],
    photos: [],
    verified: false,
    bannerColor: 'from-yellow-500 to-orange-500',
  },
  {
    id: 'co_8',
    name: 'Flipkart',
    logo: 'F',
    logoColor: 'bg-blue-500',
    industry: 'E-Commerce',
    location: 'Bangalore, India',
    size: '30,000+',
    founded: '2007',
    type: 'Private (Walmart)',
    website: 'https://flipkart.com',
    rating: 3.8,
    reviewCount: 8712,
    openJobs: 30,
    overview: 'Flipkart is India\'s leading e-commerce marketplace, backed by Walmart.',
    culture: 'Fast execution',
    careerGrowth: 'Solid',
    employeeRating: '3.8/5',
    ceo: 'Kalyan Krishnamurthy',
    highlights: ['Scale', 'Benefits', 'Tech'],
    ratingBreakdown: { 5: 35, 4: 33, 3: 20, 2: 8, 1: 4 },
    reviews: [],
    photos: [],
    verified: true,
    bannerColor: 'from-blue-500 to-blue-700',
  },
];

// ── Applications ──────────────────────────────────────────
export const applicationsData = [
  {
    id: 'app_1',
    jobTitle: 'Frontend Developer',
    company: 'Google',
    companyLogo: 'G',
    companyColor: 'bg-blue-600',
    location: 'Bangalore, India',
    workType: 'Remote',
    appliedDate: 'May 12, 2024',
    currentStage: 'Technical Interview',
    status: 'Interview',
    statusColor: 'bg-blue-50 text-blue-700 border-blue-200',
    nextStep: 'May 16, 2024 · 11:00 AM',
    nextStepLabel: 'Technical Interview with Engineering Team',
    timeline: [
      { event: 'Application Submitted', date: 'May 12, 2024 · 10:30 AM', done: true },
      { event: 'Resume Shortlisted', date: 'May 12, 2024 · 04:15 PM', done: true },
      { event: 'AI Interview Completed', date: 'May 13, 2024 · 11:20 AM', done: true },
      { event: 'Technical Interview', date: 'May 16, 2024 · 11:00 AM', done: false, upcoming: true },
      { event: 'HR Interview', date: 'Pending', done: false },
      { event: 'Offer', date: 'Pending', done: false },
    ],
    notifications: [
      { type: 'interview', text: 'Your interview has been scheduled', sub: 'Technical Interview on May 16, 2024 at 11:00 AM', date: 'May 14, 2024', icon: '📅', color: 'bg-blue-100 text-blue-700' },
      { type: 'aiinterview', text: 'AI Interview completed', sub: "Congrats! You've cleared the AI Interview round.", date: 'May 13, 2024', icon: '🤖', color: 'bg-violet-100 text-violet-700' },
      { type: 'application', text: 'Application received', sub: 'We have received your application.', date: 'May 12, 2024', icon: '✅', color: 'bg-emerald-100 text-emerald-700' },
    ],
  },
  {
    id: 'app_2',
    jobTitle: 'UI/UX Designer',
    company: 'Microsoft',
    companyLogo: 'M',
    companyColor: 'bg-orange-500',
    location: 'Noida, India',
    workType: 'Hybrid',
    appliedDate: 'May 10, 2024',
    currentStage: 'HR Round',
    status: 'Under Review',
    statusColor: 'bg-amber-50 text-amber-700 border-amber-200',
    nextStep: 'Awaiting feedback',
    nextStepLabel: 'HR screening in progress',
    timeline: [
      { event: 'Application Submitted', date: 'May 10, 2024', done: true },
      { event: 'Resume Shortlisted', date: 'May 11, 2024', done: true },
      { event: 'HR Round', date: 'May 14, 2024', done: false, upcoming: true },
    ],
    notifications: [],
  },
  {
    id: 'app_3',
    jobTitle: 'Full Stack Developer',
    company: 'Infosys',
    companyLogo: 'I',
    companyColor: 'bg-indigo-600',
    location: 'Pune, India',
    workType: 'Remote',
    appliedDate: 'May 8, 2024',
    currentStage: 'Assessment',
    status: 'Assessment',
    statusColor: 'bg-purple-50 text-purple-700 border-purple-200',
    nextStep: 'Complete assessment by May 20',
    nextStepLabel: 'Online technical assessment pending',
    timeline: [
      { event: 'Application Submitted', date: 'May 8, 2024', done: true },
      { event: 'Assessment Assigned', date: 'May 12, 2024', done: true },
      { event: 'Assessment Deadline', date: 'May 20, 2024', done: false, upcoming: true },
    ],
    notifications: [],
  },
  {
    id: 'app_4',
    jobTitle: 'Backend Engineer (Go)',
    company: 'Swiggy',
    companyLogo: 'S',
    companyColor: 'bg-orange-500',
    location: 'Bangalore, India',
    workType: 'Hybrid',
    appliedDate: 'May 5, 2024',
    currentStage: 'Online Assessment',
    status: 'Assessment',
    statusColor: 'bg-purple-50 text-purple-700 border-purple-200',
    nextStep: 'Complete coding assessment',
    nextStepLabel: 'HackerRank assessment pending',
    timeline: [
      { event: 'Application Submitted', date: 'May 5, 2024', done: true },
      { event: 'Assessment Sent', date: 'May 7, 2024', done: true },
    ],
    notifications: [],
  },
  {
    id: 'app_5',
    jobTitle: 'Product Designer',
    company: 'Amazon',
    companyLogo: 'A',
    companyColor: 'bg-yellow-600',
    location: 'Bangalore, India',
    workType: 'Remote',
    appliedDate: 'May 2, 2024',
    currentStage: 'AI Interview',
    status: 'Interview',
    statusColor: 'bg-blue-50 text-blue-700 border-blue-200',
    nextStep: 'Join AI Interview',
    nextStepLabel: 'AI Interview scheduled for May 18',
    timeline: [
      { event: 'Application Submitted', date: 'May 2, 2024', done: true },
      { event: 'Resume Shortlisted', date: 'May 5, 2024', done: true },
      { event: 'AI Interview Scheduled', date: 'May 18, 2024', done: false, upcoming: true },
    ],
    notifications: [],
  },
  {
    id: 'app_6',
    jobTitle: 'Data Analyst',
    company: 'Ola',
    companyLogo: 'O',
    companyColor: 'bg-yellow-500',
    location: 'Bangalore, India',
    workType: 'Hybrid',
    appliedDate: 'Apr 28, 2024',
    currentStage: 'Not Selected',
    status: 'Rejected',
    statusColor: 'bg-red-50 text-red-600 border-red-200',
    nextStep: 'Application closed',
    nextStepLabel: 'Not shortlisted for further rounds',
    timeline: [
      { event: 'Application Submitted', date: 'Apr 28, 2024', done: true },
      { event: 'Not Shortlisted', date: 'May 5, 2024', done: true },
    ],
    notifications: [],
  },
  {
    id: 'app_7',
    jobTitle: 'Frontend Developer Intern',
    company: 'Zomato',
    companyLogo: 'Z',
    companyColor: 'bg-red-500',
    location: 'Gurgaon, India',
    workType: 'On-site',
    appliedDate: 'Apr 25, 2024',
    currentStage: 'Withdrawn',
    status: 'Withdrawn',
    statusColor: 'bg-slate-100 text-slate-600 border-slate-200',
    nextStep: 'Application withdrawn',
    nextStepLabel: 'You withdrew this application',
    timeline: [
      { event: 'Application Submitted', date: 'Apr 25, 2024', done: true },
      { event: 'Application Withdrawn', date: 'Apr 30, 2024', done: true },
    ],
    notifications: [],
  },
  {
    id: 'app_8',
    jobTitle: 'Software Engineer',
    company: 'Flipkart',
    companyLogo: 'F',
    companyColor: 'bg-blue-500',
    location: 'Bangalore, India',
    workType: 'Remote',
    appliedDate: 'Apr 20, 2024',
    currentStage: 'Offer Extended',
    status: 'Offer',
    statusColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    nextStep: 'Accept offer by May 25, 2024',
    nextStepLabel: 'Offer letter sent to your email',
    timeline: [
      { event: 'Application Submitted', date: 'Apr 20, 2024', done: true },
      { event: 'Technical Round', date: 'Apr 28, 2024', done: true },
      { event: 'HR Round', date: 'May 5, 2024', done: true },
      { event: 'Offer Extended', date: 'May 15, 2024', done: true },
    ],
    notifications: [],
  },
];

// ── Assessments ────────────────────────────────────────────
export const assessmentsData = {
  pending: [
    {
      id: 'asmt_1',
      name: 'React Developer Assessment',
      company: 'TechNova Solutions',
      companyLogo: 'H',
      companyColor: 'bg-emerald-600',
      tags: ['React', 'JavaScript', 'Redux', 'TypeScript'],
      duration: 90,
      dueDate: 'May 16, 2024',
      dueDays: 2,
      dueUrgency: 'urgent',
    },
    {
      id: 'asmt_2',
      name: 'Frontend Skills Test',
      company: 'Pixel Perfect',
      companyLogo: 'P',
      companyColor: 'bg-violet-600',
      tags: ['HTML', 'CSS', 'JavaScript'],
      duration: 60,
      dueDate: 'May 18, 2024',
      dueDays: 4,
      dueUrgency: 'moderate',
    },
    {
      id: 'asmt_3',
      name: 'Aptitude Test',
      company: 'Accenture',
      companyLogo: 'A',
      companyColor: 'bg-blue-700',
      tags: ['Logical Reasoning', 'Quantitative', 'Verbal Ability'],
      duration: 45,
      dueDate: 'May 19, 2024',
      dueDays: 5,
      dueUrgency: 'normal',
    },
  ],
  completed: [
    {
      id: 'asmt_c1',
      name: 'TypeScript Advanced Test',
      type: 'Technical',
      company: 'Microsoft',
      companyLogo: 'M',
      companyColor: 'bg-orange-500',
      completedOn: 'May 12, 2024',
      completedTime: '10:30 AM',
      score: 88,
      maxScore: 50,
      scoreLabel: '44/50',
      status: 'Good',
      statusColor: 'text-emerald-600',
    },
    {
      id: 'asmt_c2',
      name: 'JavaScript Fundamentals',
      type: 'Technical',
      company: 'Infosys',
      companyLogo: 'I',
      companyColor: 'bg-indigo-600',
      completedOn: 'May 8, 2024',
      completedTime: '02:15 PM',
      score: 76,
      maxScore: 50,
      scoreLabel: '38/50',
      status: 'Good',
      statusColor: 'text-blue-600',
    },
    {
      id: 'asmt_c3',
      name: 'Quantitative Aptitude',
      type: 'Aptitude',
      company: 'Deloitte',
      companyLogo: 'D',
      companyColor: 'bg-green-700',
      completedOn: 'May 5, 2024',
      completedTime: '11:45 AM',
      score: 92,
      maxScore: 50,
      scoreLabel: '46/50',
      status: 'Excellent',
      statusColor: 'text-emerald-600',
    },
    {
      id: 'asmt_c4',
      name: 'Verbal Ability Test',
      type: 'Aptitude',
      company: 'Tata Consultancy Services',
      companyLogo: 'T',
      companyColor: 'bg-blue-800',
      completedOn: 'Apr 28, 2024',
      completedTime: '04:20 PM',
      score: 68,
      maxScore: 50,
      scoreLabel: '34/50',
      status: 'Average',
      statusColor: 'text-amber-600',
    },
    {
      id: 'asmt_c5',
      name: 'React Basics Test',
      type: 'Technical',
      company: 'GeekyAnts',
      companyLogo: 'G',
      companyColor: 'bg-teal-600',
      completedOn: 'Apr 24, 2024',
      completedTime: '09:10 AM',
      score: 81,
      maxScore: 50,
      scoreLabel: '40/50 + 1',
      status: 'Good',
      statusColor: 'text-blue-600',
    },
    {
      id: 'asmt_c6',
      name: 'Logical Reasoning Test',
      type: 'Aptitude',
      company: 'Wipro',
      companyLogo: 'W',
      companyColor: 'bg-indigo-500',
      completedOn: 'Apr 18, 2024',
      completedTime: '01:30 PM',
      score: 74,
      maxScore: 50,
      scoreLabel: '37/50',
      status: 'Good',
      statusColor: 'text-blue-600',
    },
  ],
  performance: {
    avgScore: 82,
    bestScore: 92,
    totalTaken: 6,
    totalTime: '5h 20m',
    strengthAreas: ['JavaScript', 'React', 'TypeScript', 'Problem Solving'],
    improveAreas: ['Verbal Ability', 'Quantitative', 'Attention to Detail'],
  },
};

// ── Interviews ─────────────────────────────────────────────
export const interviewsData = {
  upcoming: [
    {
      id: 'iv_1',
      jobTitle: 'Frontend Developer – AI Interview',
      company: 'Google',
      companyLogo: 'G',
      companyColor: 'bg-blue-600',
      location: 'Bangalore, India',
      workType: 'Remote',
      date: 'May 16, 2024',
      dateLabel: 'Tomorrow',
      timeStart: '11:00 AM',
      timeEnd: '12:00 PM',
      duration: '60 min',
      type: 'AI Interview',
      typeColor: 'bg-violet-100 text-violet-700',
      interviewId: 'TF-AI-2456',
      countdownHrs: 20,
      countdownMins: 15,
      countdownSecs: 30,
      instructions: [
        { text: 'The interview will be AI-conducted and recorded. Ensure you are in a quiet place with a stable internet connection.' },
        { text: 'Duration: 60 minutes. The interview includes a mix of technical and behavioral questions.' },
        { text: 'You may use pen & paper for problem solving. No external help or sharing screen is allowed.' },
        { text: "Be yourself and think out loud. Our AI evaluates your approach, clarity and problem solving." },
      ],
      aboutRole: 'We are looking for a Frontend Developer who is passionate about building user-friendly and scalable web applications.',
      skillsNeeded: ['React', 'JavaScript', 'TypeScript', 'HTML', 'CSS', 'Redux', 'REST APIs'],
    },
    {
      id: 'iv_2',
      jobTitle: 'UI/UX Designer – Technical Round',
      company: 'Microsoft',
      companyLogo: 'M',
      companyColor: 'bg-orange-500',
      location: 'Noida, India',
      workType: 'Hybrid',
      date: 'May 18, 2024',
      dateLabel: 'Saturday',
      timeStart: '02:30 PM',
      timeEnd: '03:30 PM',
      duration: '60 min',
      type: 'Technical',
      typeColor: 'bg-blue-100 text-blue-700',
      interviewId: 'TF-TC-1234',
      countdownHrs: 45,
      countdownMins: 30,
      countdownSecs: 0,
      instructions: [],
      aboutRole: '',
      skillsNeeded: [],
    },
    {
      id: 'iv_3',
      jobTitle: 'Full Stack Developer – HR Round',
      company: 'Infosys',
      companyLogo: 'I',
      companyColor: 'bg-indigo-600',
      location: 'Pune, India',
      workType: 'Remote',
      date: 'May 20, 2024',
      dateLabel: 'Monday',
      timeStart: '10:00 AM',
      timeEnd: '10:30 AM',
      duration: '30 min',
      type: 'HR Round',
      typeColor: 'bg-pink-100 text-pink-700',
      interviewId: 'TF-HR-7891',
      countdownHrs: 68,
      countdownMins: 0,
      countdownSecs: 0,
      instructions: [],
      aboutRole: '',
      skillsNeeded: [],
    },
  ],
  completed: [
    {
      id: 'iv_c1',
      jobTitle: 'Backend Developer',
      company: 'Amazon',
      companyLogo: 'A',
      companyColor: 'bg-yellow-600',
      type: 'Technical',
      typeColor: 'bg-blue-100 text-blue-700',
      date: 'May 12, 2024',
      time: '2:30 PM',
      aiScore: 82,
      hasFeedback: true,
      feedback: { communication: 85, confidence: 80, problemSolving: 82, technical: 81 },
      overallRating: 4.1,
    },
    {
      id: 'iv_c2',
      jobTitle: 'Backend Engineer (Go)',
      company: 'Swiggy',
      companyLogo: 'S',
      companyColor: 'bg-orange-500',
      type: 'AI Interview',
      typeColor: 'bg-violet-100 text-violet-700',
      date: 'May 10, 2024',
      time: '11:00 AM',
      aiScore: 78,
      hasFeedback: true,
      feedback: { communication: 79, confidence: 75, problemSolving: 80, technical: 78 },
      overallRating: 3.9,
    },
    {
      id: 'iv_c3',
      jobTitle: 'Product Designer',
      company: 'Ola',
      companyLogo: 'O',
      companyColor: 'bg-yellow-500',
      type: 'AI Interview',
      typeColor: 'bg-violet-100 text-violet-700',
      date: 'May 8, 2024',
      time: '04:00 PM',
      aiScore: 85,
      hasFeedback: true,
      feedback: { communication: 88, confidence: 86, problemSolving: 82, technical: 84 },
      overallRating: 4.3,
    },
    {
      id: 'iv_c4',
      jobTitle: 'Data Analyst',
      company: 'TCS',
      companyLogo: 'T',
      companyColor: 'bg-blue-800',
      type: 'HR Round',
      typeColor: 'bg-pink-100 text-pink-700',
      date: 'May 5, 2024',
      time: '03:30 PM',
      aiScore: null,
      hasFeedback: false,
      feedback: null,
      overallRating: null,
    },
    {
      id: 'iv_c5',
      jobTitle: 'Frontend Developer',
      company: 'Zomato',
      companyLogo: 'Z',
      companyColor: 'bg-red-500',
      type: 'Technical',
      typeColor: 'bg-blue-100 text-blue-700',
      date: 'May 2, 2024',
      time: '10:30 AM',
      aiScore: 74,
      hasFeedback: true,
      feedback: { communication: 72, confidence: 74, problemSolving: 76, technical: 74 },
      overallRating: 3.7,
    },
  ],
  stats: {
    upcoming: 3,
    completed: 6,
    aiInterviews: 4,
    feedbackReceived: 5,
  },
};

// ── Home Page Data ─────────────────────────────────────────
export const candidateHomeData = {
  stats: [
    { label: 'Applications', value: 18, change: '+12% this week', trend: 'up', icon: '📋', color: 'text-blue-600', bg: 'bg-blue-50' },
    { label: 'Under Review', value: 6, change: '+8% this week', trend: 'up', icon: '🔍', color: 'text-amber-600', bg: 'bg-amber-50' },
    { label: 'Interviews', value: 3, change: '+50% this week', trend: 'up', icon: '🎤', color: 'text-violet-600', bg: 'bg-violet-50' },
    { label: 'Offers', value: 1, change: '🎉 Great going!', trend: 'neutral', icon: '🎁', color: 'text-emerald-600', bg: 'bg-emerald-50' },
    { label: 'Rejections', value: 2, change: '-20% this week', trend: 'down', icon: '✕', color: 'text-red-500', bg: 'bg-red-50' },
    { label: 'Profile Views', value: 47, change: '+18% this week', trend: 'up', icon: '👁', color: 'text-primary-600', bg: 'bg-primary-50' },
  ],
  careerInsights: {
    inDemandSkill: { label: 'TypeScript', change: 'High demand • +32% this month' },
    topRole: { label: 'Frontend Developer', change: '32% more opportunities' },
    profileStrength: { label: 'Great Progress!', change: 'Keep completing your profile', pct: 65 },
  },
};
