// ─────────────────────────────────────────────────────────────
// TalentForge AI — Live Interview Mock Data
// ─────────────────────────────────────────────────────────────
import type { LiveInterview } from '../types/interview.types';

export const mockInterviews: LiveInterview[] = [
  {
    id: 'liv_001',
    title: 'Frontend Engineer — Technical Round',
    type: 'Technical',
    status: 'Live',
    meetingType: 'video',
    jobId: 'job_1',
    jobTitle: 'Senior Frontend Developer',
    company: 'Google',
    companyLogo: 'G',
    companyColor: 'bg-blue-600',
    candidateId: 'cand_001',
    candidateName: 'Aaryan Singh',
    candidateInitials: 'AS',
    candidateAvatarColor: 'from-blue-500 to-blue-700',
    candidateEmail: 'aaryan@email.com',
    recruiterIds: ['rec_001', 'rec_002'],
    date: 'Jun 28, 2026',
    dateISO: '2026-06-28',
    timeStart: '11:00 AM',
    timeEnd: '12:00 PM',
    duration: '60 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: true,
      instructions:
        'Please be on time. Ensure a quiet environment with good lighting. Keep your camera on throughout the interview. You may be asked to share your screen for coding tasks.',
    },
    createdAt: '2026-06-20T09:00:00Z',
    createdBy: 'rec_001',
    notes: '',
    roomId: 'room_liv_001',
    recordingEnabled: true,
  },
  {
    id: 'liv_002',
    title: 'HR Round — Culture & Values',
    type: 'HR Round',
    status: 'Upcoming',
    meetingType: 'video',
    jobId: 'job_2',
    jobTitle: 'Product Designer',
    company: 'Meta',
    companyLogo: 'M',
    companyColor: 'bg-blue-500',
    candidateId: 'cand_002',
    candidateName: 'Priya Sharma',
    candidateInitials: 'PS',
    candidateAvatarColor: 'from-purple-500 to-purple-700',
    candidateEmail: 'priya@email.com',
    recruiterIds: ['rec_001'],
    date: 'Jun 29, 2026',
    dateISO: '2026-06-29',
    timeStart: '2:00 PM',
    timeEnd: '2:45 PM',
    duration: '45 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: false,
      instructions:
        'This is a relaxed culture-fit conversation. Please join a few minutes early to test your connection. No coding required.',
    },
    createdAt: '2026-06-21T10:00:00Z',
    createdBy: 'rec_001',
    notes: '',
    roomId: 'room_liv_002',
    recordingEnabled: false,
  },
  {
    id: 'liv_003',
    title: 'System Design — Backend Architecture',
    type: 'System Design',
    status: 'Scheduled',
    meetingType: 'video',
    jobId: 'job_3',
    jobTitle: 'Backend Developer (Node.js)',
    company: 'Amazon',
    companyLogo: 'A',
    companyColor: 'bg-amber-600',
    candidateId: 'cand_003',
    candidateName: 'Rahul Verma',
    candidateInitials: 'RV',
    candidateAvatarColor: 'from-emerald-500 to-emerald-700',
    candidateEmail: 'rahul@email.com',
    recruiterIds: ['rec_002', 'rec_003'],
    date: 'Jul 2, 2026',
    dateISO: '2026-07-02',
    timeStart: '10:30 AM',
    timeEnd: '12:00 PM',
    duration: '90 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: true,
      instructions:
        'Prepare to design a distributed system from scratch. You will be asked to share your screen and draw architecture diagrams. Have a whiteboard tool ready.',
    },
    createdAt: '2026-06-22T11:00:00Z',
    createdBy: 'rec_002',
    notes: 'Strong system design profile. Focus on scalability.',
    roomId: 'room_liv_003',
    recordingEnabled: true,
  },
  {
    id: 'liv_004',
    title: 'Final Round — Engineering Leadership',
    type: 'Final Round',
    status: 'Scheduled',
    meetingType: 'video',
    jobId: 'job_1',
    jobTitle: 'Senior Frontend Developer',
    company: 'Google',
    companyLogo: 'G',
    companyColor: 'bg-blue-600',
    candidateId: 'cand_004',
    candidateName: 'Ananya Joshi',
    candidateInitials: 'AJ',
    candidateAvatarColor: 'from-rose-500 to-rose-700',
    candidateEmail: 'ananya@email.com',
    recruiterIds: ['rec_001', 'rec_002', 'rec_003'],
    date: 'Jul 5, 2026',
    dateISO: '2026-07-05',
    timeStart: '3:00 PM',
    timeEnd: '5:00 PM',
    duration: '120 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: true,
      instructions:
        'This is the final leadership interview. Panel of 3 interviewers. Topics include leadership principles, conflict resolution, and technical vision.',
    },
    createdAt: '2026-06-23T08:00:00Z',
    createdBy: 'rec_001',
    notes: '',
    roomId: 'room_liv_004',
    recordingEnabled: true,
  },
  {
    id: 'liv_005',
    title: 'Technical Interview — React & Performance',
    type: 'Technical',
    status: 'Completed',
    meetingType: 'video',
    jobId: 'job_1',
    jobTitle: 'Senior Frontend Developer',
    company: 'Google',
    companyLogo: 'G',
    companyColor: 'bg-blue-600',
    candidateId: 'cand_005',
    candidateName: 'Vikram Iyer',
    candidateInitials: 'VI',
    candidateAvatarColor: 'from-teal-500 to-teal-700',
    candidateEmail: 'vikram@email.com',
    recruiterIds: ['rec_002'],
    date: 'Jun 20, 2026',
    dateISO: '2026-06-20',
    timeStart: '11:00 AM',
    timeEnd: '12:00 PM',
    duration: '60 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: true,
      instructions: 'Technical round covering React patterns, performance optimisation, and browser internals.',
    },
    createdAt: '2026-06-14T09:00:00Z',
    createdBy: 'rec_002',
    notes: 'Excellent candidate. Very strong React knowledge.',
    roomId: 'room_liv_005',
    recordingEnabled: true,
  },
  {
    id: 'liv_006',
    title: 'Behavioural Interview — Leadership',
    type: 'Behavioural',
    status: 'Completed',
    meetingType: 'video',
    jobId: 'job_4',
    jobTitle: 'HR Operations Manager',
    company: 'Flipkart',
    companyLogo: 'F',
    companyColor: 'bg-yellow-500',
    candidateId: 'cand_006',
    candidateName: 'Sneha Reddy',
    candidateInitials: 'SR',
    candidateAvatarColor: 'from-amber-500 to-amber-700',
    candidateEmail: 'sneha@email.com',
    recruiterIds: ['rec_001'],
    date: 'Jun 18, 2026',
    dateISO: '2026-06-18',
    timeStart: '4:00 PM',
    timeEnd: '4:30 PM',
    duration: '30 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: false,
      instructions: 'Behavioural interview using STAR method. Prepare examples from past experiences.',
    },
    createdAt: '2026-06-12T10:00:00Z',
    createdBy: 'rec_001',
    notes: 'Good communicator. Needs follow up on leadership examples.',
    roomId: 'room_liv_006',
    recordingEnabled: false,
  },
  {
    id: 'liv_007',
    title: 'Culture Fit Interview',
    type: 'Culture Fit',
    status: 'Cancelled',
    meetingType: 'video',
    jobId: 'job_2',
    jobTitle: 'Product Designer',
    company: 'Meta',
    companyLogo: 'M',
    companyColor: 'bg-blue-500',
    candidateId: 'cand_007',
    candidateName: 'Tanmay Shah',
    candidateInitials: 'TS',
    candidateAvatarColor: 'from-violet-500 to-violet-700',
    candidateEmail: 'tanmay@email.com',
    recruiterIds: ['rec_001'],
    date: 'Jun 15, 2026',
    dateISO: '2026-06-15',
    timeStart: '2:00 PM',
    timeEnd: '2:30 PM',
    duration: '30 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: false,
      instructions: 'Cancelled by candidate.',
    },
    createdAt: '2026-06-10T11:00:00Z',
    createdBy: 'rec_001',
    notes: 'Candidate cancelled last minute.',
    roomId: 'room_liv_007',
    recordingEnabled: false,
  },
  {
    id: 'liv_008',
    title: 'Managerial Round — Product Strategy',
    type: 'Managerial',
    status: 'Missed',
    meetingType: 'video',
    jobId: 'job_3',
    jobTitle: 'Backend Developer (Node.js)',
    company: 'Amazon',
    companyLogo: 'A',
    companyColor: 'bg-amber-600',
    candidateId: 'cand_008',
    candidateName: 'Kunal Mehta',
    candidateInitials: 'KM',
    candidateAvatarColor: 'from-slate-500 to-slate-700',
    candidateEmail: 'kunal@email.com',
    recruiterIds: ['rec_003'],
    date: 'Jun 14, 2026',
    dateISO: '2026-06-14',
    timeStart: '11:00 AM',
    timeEnd: '12:00 PM',
    duration: '60 min',
    timezone: 'IST (UTC+5:30)',
    settings: {
      allowCamera: true,
      allowMicrophone: true,
      allowScreenShare: false,
      instructions: 'Candidate did not join.',
    },
    createdAt: '2026-06-08T09:00:00Z',
    createdBy: 'rec_003',
    notes: 'No show.',
    roomId: 'room_liv_008',
    recordingEnabled: true,
  },
];

// ─── Convenience getters ──────────────────────────────────────
export const getInterviewById = (id: string): LiveInterview | undefined =>
  mockInterviews.find((iv) => iv.id === id);

export const getInterviewsByStatus = (status: LiveInterview['status']): LiveInterview[] =>
  mockInterviews.filter((iv) => iv.status === status);

export const getUpcomingInterviews = (): LiveInterview[] =>
  mockInterviews.filter((iv) =>
    ['Scheduled', 'Upcoming', 'Today', 'Waiting', 'Live'].includes(iv.status)
  );

export const getCompletedInterviews = (): LiveInterview[] =>
  mockInterviews.filter((iv) =>
    ['Completed', 'Cancelled', 'Missed', 'Rescheduled'].includes(iv.status)
  );

export const getCandidateInterviews = (candidateId: string): LiveInterview[] =>
  mockInterviews.filter((iv) => iv.candidateId === candidateId);

// Stats for recruiter dashboard widget
export const liveInterviewStats = {
  totalScheduled: mockInterviews.filter((iv) => ['Scheduled', 'Upcoming', 'Today'].includes(iv.status)).length,
  live: mockInterviews.filter((iv) => iv.status === 'Live').length,
  completed: mockInterviews.filter((iv) => iv.status === 'Completed').length,
  cancelled: mockInterviews.filter((iv) => ['Cancelled', 'Missed'].includes(iv.status)).length,
  thisWeek: 5,
  avgDuration: '52 min',
};
