// ─────────────────────────────────────────────────────────────
// TalentForge AI — Participants Mock Data
// ─────────────────────────────────────────────────────────────
import type { MockRecruiter, MockCandidate, RoomParticipant } from '../types/participant.types';

// ─── Mock Recruiters / Interviewers ──────────────────────────
export const mockRecruiters: MockRecruiter[] = [
  {
    id: 'rec_001',
    name: 'Lamine Yamal',
    initials: 'LY',
    role: 'recruiter',
    title: 'Senior HR Manager',
    email: 'lamine.yamal@talentforge.ai',
    avatarColor: 'from-blue-500 to-blue-700',
    company: 'TalentForge AI',
    department: 'Human Resources',
    phone: '+91 99887 76655',
    totalInterviews: 142,
    rating: 4.8,
  },
  {
    id: 'rec_002',
    name: 'Sarah Jenkins',
    initials: 'SJ',
    role: 'interviewer',
    title: 'Lead Frontend Engineer',
    email: 'sarah.jenkins@talentforge.ai',
    avatarColor: 'from-purple-500 to-purple-700',
    company: 'TalentForge AI',
    department: 'Engineering',
    phone: '+91 98765 54321',
    totalInterviews: 87,
    rating: 4.9,
  },
  {
    id: 'rec_003',
    name: 'Arjun Kapoor',
    initials: 'AK',
    role: 'interviewer',
    title: 'Principal Backend Engineer',
    email: 'arjun.kapoor@talentforge.ai',
    avatarColor: 'from-emerald-500 to-emerald-700',
    company: 'TalentForge AI',
    department: 'Engineering',
    phone: '+91 97654 43210',
    totalInterviews: 63,
    rating: 4.7,
  },
];

// ─── Mock Candidates ──────────────────────────────────────────
export const mockCandidates: MockCandidate[] = [
  {
    id: 'cand_001',
    name: 'Aaryan Singh',
    initials: 'AS',
    role: 'candidate',
    title: 'Senior Frontend Developer',
    email: 'aaryan@email.com',
    avatarColor: 'from-blue-500 to-blue-700',
    jobTitle: 'Senior Frontend Developer',
    experience: '4 years',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'GraphQL'],
    resumeUrl: '#',
  },
  {
    id: 'cand_002',
    name: 'Priya Sharma',
    initials: 'PS',
    role: 'candidate',
    title: 'Product Designer',
    email: 'priya@email.com',
    avatarColor: 'from-purple-500 to-purple-700',
    jobTitle: 'Product Designer',
    experience: '3 years',
    skills: ['Figma', 'UI/UX', 'Design Systems', 'Prototyping', 'User Research'],
    resumeUrl: '#',
  },
  {
    id: 'cand_003',
    name: 'Rahul Verma',
    initials: 'RV',
    role: 'candidate',
    title: 'Backend Developer',
    email: 'rahul@email.com',
    avatarColor: 'from-emerald-500 to-emerald-700',
    jobTitle: 'Backend Developer (Node.js)',
    experience: '5 years',
    skills: ['Node.js', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    resumeUrl: '#',
  },
  {
    id: 'cand_004',
    name: 'Ananya Joshi',
    initials: 'AJ',
    role: 'candidate',
    title: 'Frontend Engineer',
    email: 'ananya@email.com',
    avatarColor: 'from-rose-500 to-rose-700',
    jobTitle: 'Senior Frontend Developer',
    experience: '6 years',
    skills: ['React', 'Vue.js', 'TypeScript', 'Web Performance', 'Testing'],
    resumeUrl: '#',
  },
  {
    id: 'cand_005',
    name: 'Vikram Iyer',
    initials: 'VI',
    role: 'candidate',
    title: 'Frontend Developer',
    email: 'vikram@email.com',
    avatarColor: 'from-teal-500 to-teal-700',
    jobTitle: 'Senior Frontend Developer',
    experience: '3.5 years',
    skills: ['React', 'JavaScript', 'CSS', 'Redux', 'Jest'],
    resumeUrl: '#',
  },
  {
    id: 'cand_006',
    name: 'Sneha Reddy',
    initials: 'SR',
    role: 'candidate',
    title: 'HR Operations Manager',
    email: 'sneha@email.com',
    avatarColor: 'from-amber-500 to-amber-700',
    jobTitle: 'HR Operations Manager',
    experience: '7 years',
    skills: ['Talent Acquisition', 'HRIS', 'Employee Relations', 'Compliance', 'Training'],
    resumeUrl: '#',
  },
  {
    id: 'cand_007',
    name: 'Tanmay Shah',
    initials: 'TS',
    role: 'candidate',
    title: 'Product Designer',
    email: 'tanmay@email.com',
    avatarColor: 'from-violet-500 to-violet-700',
    jobTitle: 'Product Designer',
    experience: '2 years',
    skills: ['Figma', 'Adobe XD', 'Sketch', 'Wireframing', 'User Testing'],
    resumeUrl: '#',
  },
  {
    id: 'cand_008',
    name: 'Kunal Mehta',
    initials: 'KM',
    role: 'candidate',
    title: 'Backend Developer',
    email: 'kunal@email.com',
    avatarColor: 'from-slate-500 to-slate-700',
    jobTitle: 'Backend Developer (Node.js)',
    experience: '4 years',
    skills: ['Node.js', 'MongoDB', 'Express.js', 'Microservices', 'Kubernetes'],
    resumeUrl: '#',
  },
];

// ─── Room Participants for liv_001 (current live interview) ───
export const mockRoomParticipants: RoomParticipant[] = [
  {
    id: 'rec_001',
    name: 'Lamine Yamal',
    initials: 'LY',
    role: 'recruiter',
    title: 'Senior HR Manager',
    email: 'lamine.yamal@talentforge.ai',
    avatarColor: 'from-blue-500 to-blue-700',
    isMicOn: true,
    isCameraOn: true,
    isScreenSharing: false,
    isSpeaking: false,
    connectionStatus: 'excellent',
    joinedAt: '11:01 AM',
    isPinned: false,
    isHandRaised: false,
  },
  {
    id: 'rec_002',
    name: 'Sarah Jenkins',
    initials: 'SJ',
    role: 'interviewer',
    title: 'Lead Frontend Engineer',
    email: 'sarah.jenkins@talentforge.ai',
    avatarColor: 'from-purple-500 to-purple-700',
    isMicOn: false,
    isCameraOn: true,
    isScreenSharing: false,
    isSpeaking: false,
    connectionStatus: 'good',
    joinedAt: '11:02 AM',
    isPinned: false,
    isHandRaised: false,
  },
  {
    id: 'cand_001',
    name: 'Aaryan Singh',
    initials: 'AS',
    role: 'candidate',
    title: 'Senior Frontend Developer',
    email: 'aaryan@email.com',
    avatarColor: 'from-blue-500 to-blue-700',
    isMicOn: true,
    isCameraOn: true,
    isScreenSharing: false,
    isSpeaking: true,
    connectionStatus: 'excellent',
    joinedAt: '10:59 AM',
    isPinned: false,
    isHandRaised: false,
  },
];

// ─── Current User (candidate mode) ───────────────────────────
export const mockCurrentUserCandidate = {
  id: 'cand_001',
  name: 'Aaryan Singh',
  initials: 'AS',
  role: 'candidate' as const,
  title: 'Senior Frontend Developer',
  avatarColor: 'from-blue-500 to-blue-700',
  isMicOn: true,
  isCameraOn: true,
  isScreenSharing: false,
};

// ─── Current User (recruiter mode) ───────────────────────────
export const mockCurrentUserRecruiter = {
  id: 'rec_001',
  name: 'Lamine Yamal',
  initials: 'LY',
  role: 'recruiter' as const,
  title: 'Senior HR Manager',
  avatarColor: 'from-blue-500 to-blue-700',
  isMicOn: true,
  isCameraOn: true,
  isScreenSharing: false,
};

// ─── Helpers ─────────────────────────────────────────────────
export const getRecruiterById = (id: string) =>
  mockRecruiters.find((r) => r.id === id);

export const getCandidateById = (id: string) =>
  mockCandidates.find((c) => c.id === id);

export const getRecruitersByIds = (ids: string[]) =>
  mockRecruiters.filter((r) => ids.includes(r.id));
